# Generated by Django 5.1.2 on 2024-10-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Escreva a descrição da sua tarefa', max_length=2500, verbose_name='Descrição'),
        ),
    ]
